# generated by craft based on the runenv define

XDG_DATA_DIRS="$this_dir/usr/share/:$XDG_DATA_DIRS:/usr/local/share:/usr/share"
export XDG_DATA_DIRS
FONTCONFIG_PATH="$(if [ -d /etc/fonts ]; then echo "/etc/fonts"; else echo "$this_dir/etc/fonts"; fi)"
export FONTCONFIG_PATH
PATH="$this_dir/usr/bin:$this_dir/usr/lib:$PATH"
export PATH
PACKAGE_TYPE=appimage
export PACKAGE_TYPE
MLT_REPOSITORY=$this_dir/usr/lib/mlt-7/
export MLT_REPOSITORY
MLT_DATA=$this_dir/usr/share/mlt-7/
export MLT_DATA
MLT_ROOT_DIR=$this_dir/usr/
export MLT_ROOT_DIR
MLT_APPDIR=$this_dir/usr/
export MLT_APPDIR
LADSPA_PATH=$this_dir/usr/lib/ladspa
export LADSPA_PATH
FREI0R_PATH=$this_dir/usr/lib/frei0r-1
export FREI0R_PATH
MLT_PROFILES_PATH=$this_dir/usr/share/mlt-7/profiles/
export MLT_PROFILES_PATH
MLT_PRESETS_PATH=$this_dir/usr/share/mlt-7/presets/
export MLT_PRESETS_PATH
SDL_AUDIODRIVER=pulseaudio
export SDL_AUDIODRIVER
ALSA_CONFIG_DIR=/usr/share/alsa
export ALSA_CONFIG_DIR
ALSA_PLUGIN_DIR=/usr/lib/x86_64-linux-gnu/alsa-lib
export ALSA_PLUGIN_DIR
LIBVA_DRIVERS_PATH=/usr/lib/dri:/usr/lib64/dri:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/aarch64-linux-gnu/dri
export LIBVA_DRIVERS_PATH
